from metaphone import doublemetaphone
import jellyfish


print(type(doublemetaphone("architect")))
print(doublemetaphone("apple"))

print(doublemetaphone("daryl"), doublemetaphone("darrel"))
print(doublemetaphone("daryl"), doublemetaphone("darryl"))
print(doublemetaphone("gerry"), doublemetaphone("gary"))
print(doublemetaphone("daniel"), doublemetaphone("tane"))
print(doublemetaphone("daniel"), doublemetaphone("tenniel"))
print(doublemetaphone("cindy"), doublemetaphone("sindy"))
print(doublemetaphone("awana"), doublemetaphone("wana"))
print(doublemetaphone("les"), doublemetaphone("less"))
print(doublemetaphone("marylin"), doublemetaphone("maryland"))


print("MRA")
print(jellyfish.match_rating_comparison('daryl', 'darrel'))
print(jellyfish.match_rating_comparison('daryl', 'darryl'))
print(jellyfish.match_rating_comparison('gerry', 'gary'))
print(jellyfish.match_rating_comparison('daniel', 'tane'))
print(jellyfish.match_rating_comparison('daniel', 'tenniel'))
print(jellyfish.match_rating_comparison('cindy', 'sindy'))
print(jellyfish.match_rating_comparison('awana', 'wana'))
print(jellyfish.match_rating_comparison('les', 'less'))
print(jellyfish.match_rating_comparison('marylin', 'maryland'))

print(jellyfish.match_rating_comparison('be', 'is'))

print('jellyfish.match_rating_codex')
print(jellyfish.match_rating_codex('daryl'), jellyfish.match_rating_codex('darryl'))
print(jellyfish.match_rating_codex('daryl'), jellyfish.match_rating_codex('darryl'))
print(jellyfish.match_rating_codex('gerry'), jellyfish.match_rating_codex('gary'))
print(jellyfish.match_rating_codex('daniel'), jellyfish.match_rating_codex('tane'))
print(jellyfish.match_rating_codex('cindy'), jellyfish.match_rating_codex('sindy'))
print(jellyfish.match_rating_codex('awana'), jellyfish.match_rating_codex('wana'))
print(jellyfish.match_rating_codex('les'), jellyfish.match_rating_codex('less'))
print(jellyfish.match_rating_codex('marylin'), jellyfish.match_rating_codex('maryland'))

print('not names')
print(jellyfish.match_rating_comparison('enriched', 'enrich'))
print(jellyfish.match_rating_comparison('tonight  ', 'to night '))
print(jellyfish.match_rating_comparison("daniel's", 'daniel is'))
print(jellyfish.match_rating_comparison('oh  ', 'o '))
print(jellyfish.match_rating_comparison('lords', 'lord'))
print(jellyfish.match_rating_comparison("nebuchadnezzar's", "nebuchadnezzars's"))
print(jellyfish.match_rating_comparison("i've", 'ive'))
print(jellyfish.match_rating_comparison('eighteen  ', 'eighteenth '))
print(jellyfish.match_rating_comparison("Incredible", 'credible'))
print(jellyfish.match_rating_comparison("I’m", 'I am '))
print('DM')
print(doublemetaphone("enriched"), doublemetaphone("enrich"))
print(doublemetaphone("tonight"), doublemetaphone("to night"))
print(doublemetaphone("daniel's"), doublemetaphone("daniel is"))
print(doublemetaphone("oh"), doublemetaphone("o"))
print(doublemetaphone("lords"), doublemetaphone("lord"))
print(doublemetaphone("nebuchadnezzar's"), doublemetaphone("nebuchadnezzars's"))
print(doublemetaphone("i've"), doublemetaphone("ive"))
print(doublemetaphone("eighteen"), doublemetaphone("eighteenth"))
print(doublemetaphone("Incredible"), doublemetaphone("credible"))
print(doublemetaphone("I’m"), doublemetaphone("I am"))

print('they are not same at all')
print(jellyfish.match_rating_comparison('amen', 'and then'))
print(jellyfish.match_rating_comparison('amen', 'a an men'))
print(jellyfish.match_rating_comparison("in", 'yeah'))
print(jellyfish.match_rating_comparison('us  ', 'so '))
print(jellyfish.match_rating_comparison("nebuchadnezzar's", ""))

print('DM')
print(doublemetaphone("amen"), doublemetaphone("and then"))
print(doublemetaphone("amen"), doublemetaphone("a an men"))
print(doublemetaphone("in"), doublemetaphone("yeah"))
print(doublemetaphone("us"), doublemetaphone("so"))
print(doublemetaphone("nebuchadnezzar's"), doublemetaphone(" "))
